# Generated by Django 6.0.2 on 2026-02-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default='gray', help_text='Color hex, ej: #ff0000 o nombre de color', max_length=20),
        ),
    ]
